### ISSUE TITLE
Config deleted when closing the game

### ISSUE THREAD

**Issue by Nuaja** [EnnuiL/BoringDefaultGameRules#2]
When I close and restart my game, the config resets...
(using 1.19.2 Quilt)

**Comment by EnnuiL** [comment]
Sorry for the delay; I've attempted to reproduce this issue, however, yeah, I failed to get any sort of config loss between restarts

**Comment by JLUsr** [comment]
> When I close and restart my game, the config resets... (using 1.19.2 Quilt)

If you are willing to share your complete mod list as well as the gamerules you were trying to change the default for I am willing to attempt reproducing and filtering this issue.

**Comment by EnnuiL** [comment]
I feel like it's safe to assume that the actual cause of this issue is the one related on issue #3: the fact that number values had a wrong assumption by both Quilt Config and myself that resulted on this crash; A fix will come tomorrow
